# Generated by Django 4.0.4 on 2022-05-26 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('becas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beca',
            name='vistas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='root',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
